language: python
branches:
    only:
        - master
python:
    - "2.6"
    - "2.7"
    - "3.3"
install:
    - pip install -r requirements-dev.txt
    - pip install coveralls
script:
    - py.test --cov=pyswagger --cov-config=.coveragerc pyswagger/tests
after_success:
    - coveralls

